from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import json

from fastapi.testclient import TestClient

from app.game import Phase

OUTPUT_ROOT = Path("test.folder")


class ScreenshotKit:
    """Builds a phase-by-phase capture kit under test.folder/."""

    def __init__(self, root: Path = OUTPUT_ROOT):
        self.root = root
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        self.run_dir = self.root / f"run_{timestamp}"
        self.run_dir.mkdir(parents=True, exist_ok=True)
        self.records: list[dict[str, str]] = []

    def capture_phase(
        self,
        client: TestClient,
        *,
        code: str,
        host_token: str,
        phase: Phase,
        sequence: int,
    ) -> None:
        slug = phase.value
        state = client.get(f"/api/state/{code}", params={"token": host_token}).json()
        host_html = client.get("/host", params={"token": host_token}).text

        state_path = self.run_dir / f"{sequence:02d}_{slug}_state.json"
        host_path = self.run_dir / f"{sequence:02d}_{slug}_host.html"

        state_path.write_text(json.dumps(state, indent=2), encoding="utf-8")
        host_path.write_text(host_html, encoding="utf-8")

        self.records.append(
            {
                "phase": phase.value,
                "state": state_path.name,
                "host": host_path.name,
            }
        )

    def finalize(self) -> Path:
        lines = [
            "# Test Screenshot Kit",
            "",
            "This folder is generated by automated tests.",
            "",
            "## Captured phases",
            "",
        ]
        for idx, rec in enumerate(self.records, start=1):
            lines.append(
                f"{idx}. `{rec['phase']}` -> `{rec['state']}` and `{rec['host']}`"
            )

        summary_path = self.run_dir / "SUMMARY.md"
        summary_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return summary_path
